#!/usr/bin/env bash
# Publishes every shard in data/shards.json as its own public repo
# <owner>/immersive-cdn-NN, tagged $CDN_TAG, so jsDelivr sees repos under 50 MB.
#
#   CDN_OWNER=<github user> CDN_TAG=v1.0.0 ./scripts/publish-shards.sh
#
# Needs `gh auth login`. A shard repo that already has the tag is skipped:
# a published tag is what the app points at, and it must never change.
set -euo pipefail
: "${CDN_OWNER:?CDN_OWNER is required}"
CDN_TAG="${CDN_TAG:-v1.0.0}"

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
GIT=(git -c credential.helper= -c 'credential.helper=!gh auth git-credential')

for shard in $(jq -r '[.[]] | unique | .[]' data/shards.json); do
  repo="immersive-cdn-$shard"
  if gh api "repos/$CDN_OWNER/$repo/git/refs/tags/$CDN_TAG" >/dev/null 2>&1; then
    echo "• $repo@$CDN_TAG already published"; continue
  fi
  echo "▸ $repo"
  dir=".shards/$repo"
  rm -rf "$dir"; mkdir -p "$dir/videos" "$dir/thumbnails"
  for id in $(jq -r --arg s "$shard" 'to_entries[] | select(.value == $s) | .key' data/shards.json); do
    cp "videos/$id.mp4" "$dir/videos/"
    cp "thumbnails/$id.jpg" "$dir/thumbnails/"
  done
  cat > "$dir/README.md" <<MD
# $repo

Shard $shard of the Immersive iOS app media, served through jsDelivr:

    https://cdn.jsdelivr.net/gh/$CDN_OWNER/$repo@$CDN_TAG/videos/<documentId>.mp4
    https://cdn.jsdelivr.net/gh/$CDN_OWNER/$repo@$CDN_TAG/thumbnails/<documentId>.jpg

Generated by \`scripts/publish-shards.sh\` in $CDN_OWNER/immersive-cdn — do not edit by hand.
Kept under 45 MB because jsDelivr rejects GitHub repos over 50 MB.
MD
  gh repo view "$CDN_OWNER/$repo" >/dev/null 2>&1 \
    || gh repo create "$CDN_OWNER/$repo" --public \
         --description "Immersive iOS media shard $shard (jsDelivr)" >/dev/null
  (
    cd "$dir"
    git init -q -b main
    git add -A
    git -c user.name="$(git -C "$ROOT" log -1 --format=%an)" \
        -c user.email="$(git -C "$ROOT" log -1 --format=%ae)" \
        commit -qm "Shard $shard $CDN_TAG"
    git tag "$CDN_TAG"
    "${GIT[@]}" push -q "https://github.com/$CDN_OWNER/$repo.git" main "$CDN_TAG"
  )
done
echo "✓ shards published"
